// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimeScore.Modules.Configuration.Storage;

#nullable disable

namespace PrimeScore.Modules.Configuration.Storage.Migrations
{
    [DbContext(typeof(ConfigurationDbContext))]
    [Migration("20260925080231_InitialConfiguration")]
    partial class InitialConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("PrimeScore.Modules.Configuration.Storage.SettingsRow", b =>
                {
                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("changed_by");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("changes");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<long>("RecordedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recorded_at_ms");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ledger_sequence");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("settings");

                    b.HasKey("Version");

                    b.HasIndex("Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_cfg_versions_sequence");

                    b.ToTable("cfg_versions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
