// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimeScore.Modules.Ingestion.Storage;

#nullable disable

namespace PrimeScore.Modules.Ingestion.Storage.Migrations
{
    [DbContext(typeof(IngestionDbContext))]
    partial class IngestionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("PrimeScore.Modules.Ingestion.Storage.RejectionRow", b =>
                {
                    b.Property<string>("RejectionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("rejection_id");

                    b.Property<string>("Errors")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("errors");

                    b.Property<string>("Raw")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("raw");

                    b.Property<long>("RecordedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recorded_at_ms");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ledger_sequence");

                    b.Property<string>("SourceIdentifier")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_identifier");

                    b.HasKey("RejectionId");

                    b.HasIndex("Sequence")
                        .HasDatabaseName("ix_ing_rejections_sequence");

                    b.ToTable("ing_rejections", (string)null);
                });

            modelBuilder.Entity("PrimeScore.Modules.Ingestion.Storage.SignalRow", b =>
                {
                    b.Property<string>("SignalId")
                        .HasColumnType("TEXT")
                        .HasColumnName("signal_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("instrument");

                    b.Property<long>("ObservedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("observed_at_ms");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.Property<string>("PayloadType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_type");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("provenance");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("provider");

                    b.Property<long>("RecordedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recorded_at_ms");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ledger_sequence");

                    b.Property<string>("SourceIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_identifier");

                    b.Property<double?>("Value")
                        .HasColumnType("REAL")
                        .HasColumnName("value");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("variant");

                    b.HasKey("SignalId");

                    b.HasIndex("ObservedAtMs")
                        .HasDatabaseName("ix_ing_signals_time");

                    b.HasIndex("Category", "ObservedAtMs")
                        .HasDatabaseName("ix_ing_signals_category_time");

                    b.HasIndex("Provider", "SourceIdentifier", "ObservedAtMs")
                        .HasDatabaseName("ix_ing_signals_provider");

                    b.HasIndex("Instrument", "Category", "Variant", "ObservedAtMs")
                        .HasDatabaseName("ix_ing_signals_series_time");

                    b.HasIndex("SourceIdentifier", "Instrument", "Variant", "ObservedAtMs")
                        .IsUnique()
                        .HasDatabaseName("ux_ing_signals_key");

                    b.ToTable("ing_signals", (string)null);
                });

            modelBuilder.Entity("PrimeScore.Modules.Ingestion.Storage.SourceRunRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Accepted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("accepted");

                    b.Property<int>("Duplicates")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duplicates");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<long?>("FinishedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("finished_at_ms");

                    b.Property<int>("Missing")
                        .HasColumnType("INTEGER")
                        .HasColumnName("missing");

                    b.Property<int>("Rejected")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rejected");

                    b.Property<int>("Revised")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revised");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<long>("StartedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("started_at_ms");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("INTEGER")
                        .HasColumnName("succeeded");

                    b.HasKey("Id");

                    b.HasIndex("Source", "StartedAtMs")
                        .HasDatabaseName("ix_ing_source_runs_source_time");

                    b.ToTable("ing_source_runs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
