// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimeScore.Modules.Classification.Storage;

#nullable disable

namespace PrimeScore.Modules.Classification.Storage.Migrations
{
    [DbContext(typeof(ClassificationDbContext))]
    [Migration("20260925085751_AddAggregates")]
    partial class AddAggregates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("PrimeScore.Modules.Classification.Storage.AssessmentRow", b =>
                {
                    b.Property<string>("AssessmentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("assessment_id");

                    b.Property<long>("AssessedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("assessed_at_ms");

                    b.Property<bool>("Available")
                        .HasColumnType("INTEGER")
                        .HasColumnName("available");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<double?>("Certainty")
                        .HasColumnType("REAL")
                        .HasColumnName("certainty");

                    b.Property<string>("ClassificationMethod")
                        .HasColumnType("TEXT")
                        .HasColumnName("classification_method");

                    b.Property<string>("ComputedMetrics")
                        .HasColumnType("TEXT")
                        .HasColumnName("computed_metrics");

                    b.Property<string>("Consensus")
                        .HasColumnType("TEXT")
                        .HasColumnName("consensus");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT")
                        .HasColumnName("detail");

                    b.Property<string>("EventTaxonomy")
                        .HasColumnType("TEXT")
                        .HasColumnName("event_taxonomy");

                    b.Property<string>("FallbackOf")
                        .HasColumnType("TEXT")
                        .HasColumnName("fallback_of");

                    b.Property<string>("Flags")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("flags");

                    b.Property<double?>("HistorySufficiency")
                        .HasColumnType("REAL")
                        .HasColumnName("history_sufficiency");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("http_status");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("instrument");

                    b.Property<bool>("IsFallback")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_fallback");

                    b.Property<long>("ObservedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("observed_at_ms");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<string>("ReasoningTrace")
                        .HasColumnType("TEXT")
                        .HasColumnName("reasoning_trace");

                    b.Property<int>("ReferenceWindowLength")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reference_window_length");

                    b.Property<double?>("Score")
                        .HasColumnType("REAL")
                        .HasColumnName("score");

                    b.Property<string>("ScoreType")
                        .HasColumnType("TEXT")
                        .HasColumnName("score_type");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ledger_sequence");

                    b.Property<string>("SignalId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("signal_id");

                    b.Property<double?>("StalenessSeconds")
                        .HasColumnType("REAL")
                        .HasColumnName("staleness_seconds");

                    b.Property<double?>("TemporalRelevance")
                        .HasColumnType("REAL")
                        .HasColumnName("temporal_relevance");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("variant");

                    b.HasKey("AssessmentId");

                    b.HasIndex("ObservedAtMs")
                        .HasDatabaseName("ix_cls_assessments_time");

                    b.HasIndex("SignalId", "Sequence")
                        .HasDatabaseName("ix_cls_assessments_signal");

                    b.HasIndex("Instrument", "Category", "Variant", "ObservedAtMs")
                        .HasDatabaseName("ix_cls_assessments_series_time");

                    b.ToTable("cls_assessments", (string)null);
                });

            modelBuilder.Entity("PrimeScore.Modules.Classification.Storage.CompositeRow", b =>
                {
                    b.Property<string>("CompositeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("composite_id");

                    b.Property<string>("Absent")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("absent");

                    b.Property<string>("Aggregation")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("aggregation");

                    b.Property<long>("AsOfMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("as_of_ms");

                    b.Property<long>("ComputedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("computed_at_ms");

                    b.Property<int>("ConfigVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("config_version");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("context");

                    b.Property<string>("Contributing")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("contributing");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("correlation_id");

                    b.Property<double>("Score")
                        .HasColumnType("REAL")
                        .HasColumnName("score");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ledger_sequence");

                    b.Property<string>("TriggerAssessmentId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("trigger_assessment_id");

                    b.Property<string>("TriggerSignalId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("trigger_signal_id");

                    b.Property<string>("WeightingSchemeId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("weighting_scheme_id");

                    b.HasKey("CompositeId");

                    b.HasIndex("Context", "TriggerAssessmentId")
                        .HasDatabaseName("ix_cls_composites_trigger");

                    b.HasIndex("Context", "AsOfMs", "Sequence")
                        .HasDatabaseName("ix_cls_composites_context_time");

                    b.ToTable("cls_composites", (string)null);
                });

            modelBuilder.Entity("PrimeScore.Modules.Classification.Storage.DislocationRow", b =>
                {
                    b.Property<string>("DislocationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("dislocation_id");

                    b.Property<long>("AsOfMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("as_of_ms");

                    b.Property<string>("CompositeId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("composite_id");

                    b.Property<double>("CompositeScore")
                        .HasColumnType("REAL")
                        .HasColumnName("composite_score");

                    b.Property<long>("ComputedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("computed_at_ms");

                    b.Property<int>("ConfigVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("config_version");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("context");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("correlation_id");

                    b.Property<double>("DislocationValue")
                        .HasColumnType("REAL")
                        .HasColumnName("dislocation_value");

                    b.Property<long>("IvObservedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("iv_observed_at_ms");

                    b.Property<string>("IvSignalId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("iv_signal_id");

                    b.Property<double>("MarketObservedIv")
                        .HasColumnType("REAL")
                        .HasColumnName("market_observed_iv");

                    b.Property<string>("ReferenceInstrument")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reference_instrument");

                    b.Property<string>("Regime")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("regime");

                    b.Property<int>("RegimeHistory")
                        .HasColumnType("INTEGER")
                        .HasColumnName("regime_history");

                    b.Property<double?>("RegimePercentile")
                        .HasColumnType("REAL")
                        .HasColumnName("regime_percentile");

                    b.Property<double>("SensitivityFactor")
                        .HasColumnType("REAL")
                        .HasColumnName("sensitivity_factor");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ledger_sequence");

                    b.Property<double>("SignalImpliedIv")
                        .HasColumnType("REAL")
                        .HasColumnName("signal_implied_iv");

                    b.Property<double>("Threshold")
                        .HasColumnType("REAL")
                        .HasColumnName("threshold");

                    b.Property<bool>("ThresholdBreached")
                        .HasColumnType("INTEGER")
                        .HasColumnName("threshold_breached");

                    b.HasKey("DislocationId");

                    b.HasIndex("CompositeId")
                        .HasDatabaseName("ix_cls_dislocations_composite");

                    b.HasIndex("Context", "AsOfMs", "Sequence")
                        .HasDatabaseName("ix_cls_dislocations_context_time");

                    b.ToTable("cls_dislocations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
