// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimeScore.Modules.Classification.Storage;

#nullable disable

namespace PrimeScore.Modules.Classification.Storage.Migrations
{
    [DbContext(typeof(ClassificationDbContext))]
    partial class ClassificationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("PrimeScore.Modules.Classification.Storage.AssessmentRow", b =>
                {
                    b.Property<string>("AssessmentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("assessment_id");

                    b.Property<long>("AssessedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("assessed_at_ms");

                    b.Property<bool>("Available")
                        .HasColumnType("INTEGER")
                        .HasColumnName("available");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<double?>("Certainty")
                        .HasColumnType("REAL")
                        .HasColumnName("certainty");

                    b.Property<string>("ClassificationMethod")
                        .HasColumnType("TEXT")
                        .HasColumnName("classification_method");

                    b.Property<string>("ComputedMetrics")
                        .HasColumnType("TEXT")
                        .HasColumnName("computed_metrics");

                    b.Property<string>("Consensus")
                        .HasColumnType("TEXT")
                        .HasColumnName("consensus");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT")
                        .HasColumnName("detail");

                    b.Property<string>("EventTaxonomy")
                        .HasColumnType("TEXT")
                        .HasColumnName("event_taxonomy");

                    b.Property<string>("FallbackOf")
                        .HasColumnType("TEXT")
                        .HasColumnName("fallback_of");

                    b.Property<string>("Flags")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("flags");

                    b.Property<double?>("HistorySufficiency")
                        .HasColumnType("REAL")
                        .HasColumnName("history_sufficiency");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("http_status");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("instrument");

                    b.Property<bool>("IsFallback")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_fallback");

                    b.Property<long>("ObservedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("observed_at_ms");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<string>("ReasoningTrace")
                        .HasColumnType("TEXT")
                        .HasColumnName("reasoning_trace");

                    b.Property<int>("ReferenceWindowLength")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reference_window_length");

                    b.Property<double?>("Score")
                        .HasColumnType("REAL")
                        .HasColumnName("score");

                    b.Property<string>("ScoreType")
                        .HasColumnType("TEXT")
                        .HasColumnName("score_type");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ledger_sequence");

                    b.Property<string>("SignalId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("signal_id");

                    b.Property<double?>("StalenessSeconds")
                        .HasColumnType("REAL")
                        .HasColumnName("staleness_seconds");

                    b.Property<double?>("TemporalRelevance")
                        .HasColumnType("REAL")
                        .HasColumnName("temporal_relevance");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("variant");

                    b.HasKey("AssessmentId");

                    b.HasIndex("ObservedAtMs")
                        .HasDatabaseName("ix_cls_assessments_time");

                    b.HasIndex("SignalId", "Sequence")
                        .HasDatabaseName("ix_cls_assessments_signal");

                    b.HasIndex("Instrument", "Category", "Variant", "ObservedAtMs")
                        .HasDatabaseName("ix_cls_assessments_series_time");

                    b.ToTable("cls_assessments", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
