// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimeScore.Ledger.Storage;

#nullable disable

namespace PrimeScore.Ledger.Storage.Migrations
{
    [DbContext(typeof(LedgerDbContext))]
    [Migration("20260924230243_HardenAppendOnly")]
    partial class HardenAppendOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("PrimeScore.Ledger.Storage.LedgerRow", b =>
                {
                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence");

                    b.Property<int>("ConfigVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("config_version");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_id");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("hash");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.Property<string>("PrevHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("prev_hash");

                    b.Property<string>("RecordedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_at");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.HasKey("Sequence");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_ledger_correlation_id");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("ix_ledger_entity_id");

                    b.HasIndex("Kind")
                        .HasDatabaseName("ix_ledger_kind");

                    b.ToTable("ledger", (string)null);
                });

            modelBuilder.Entity("PrimeScore.Ledger.Storage.PipelineLogRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ConfigVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("config_version");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("stage");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_obs_log_correlation_id");

                    b.ToTable("obs_log", (string)null);
                });

            modelBuilder.Entity("PrimeScore.Ledger.Storage.VerificationRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("EntriesChecked")
                        .HasColumnType("INTEGER")
                        .HasColumnName("entries_checked");

                    b.Property<long?>("FirstInvalidSequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("first_invalid_sequence");

                    b.Property<string>("HeadHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("head_hash");

                    b.Property<long>("HeadSequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("head_sequence");

                    b.Property<bool>("Ok")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ok");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<string>("VerifiedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("verified_at");

                    b.HasKey("Id");

                    b.ToTable("ledger_verifications", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
