// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimeScore.Modules.Catalysts.Storage;

#nullable disable

namespace PrimeScore.Modules.Catalysts.Storage.Migrations
{
    [DbContext(typeof(CatalystsDbContext))]
    [Migration("20260929121153_InitialCatalysts")]
    partial class InitialCatalysts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("PrimeScore.Modules.Catalysts.Storage.CatalystEventRow", b =>
                {
                    b.Property<string>("CatalystId")
                        .HasColumnType("TEXT")
                        .HasColumnName("catalyst_id");

                    b.Property<int>("Vintage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("vintage");

                    b.Property<long?>("ActualAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("actual_at_ms");

                    b.Property<string>("Adapter")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("adapter");

                    b.Property<bool>("Backfilled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("backfilled");

                    b.Property<string>("Change")
                        .HasColumnType("TEXT")
                        .HasColumnName("change");

                    b.Property<bool>("CountedReschedule")
                        .HasColumnType("INTEGER")
                        .HasColumnName("counted_reschedule");

                    b.Property<string>("Derivation")
                        .HasColumnType("TEXT")
                        .HasColumnName("derivation");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("family");

                    b.Property<string>("FileSha256")
                        .HasColumnType("TEXT")
                        .HasColumnName("file_sha256");

                    b.Property<long>("FirstAnnouncedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("first_announced_at_ms");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_current");

                    b.Property<string>("LedgerHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ledger_hash");

                    b.Property<long>("RecordedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recorded_at_ms");

                    b.Property<string>("ReferencePeriod")
                        .HasColumnType("TEXT")
                        .HasColumnName("reference_period");

                    b.Property<long>("RetrievedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("retrieved_at_ms");

                    b.Property<long>("ScheduledAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scheduled_at_ms");

                    b.Property<string>("ScheduledDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("scheduled_date");

                    b.Property<bool?>("Sep")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sep");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ledger_sequence");

                    b.Property<string>("SourceKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_key");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_kind");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<bool>("Tentative")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tentative");

                    b.Property<bool>("TimeAnnounced")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time_announced");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("CatalystId", "Vintage");

                    b.HasIndex("Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_cat_events_sequence");

                    b.HasIndex("SourceUrl")
                        .HasDatabaseName("ix_cat_events_source_url");

                    b.HasIndex("Family", "ScheduledAtMs")
                        .HasDatabaseName("ix_cat_events_family_time");

                    b.HasIndex("Family", "SourceKey")
                        .HasDatabaseName("ix_cat_events_source_key");

                    b.HasIndex("IsCurrent", "ScheduledAtMs")
                        .HasDatabaseName("ix_cat_events_current_time");

                    b.ToTable("cat_events", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
