// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimeScore.Modules.Decision.Storage;

#nullable disable

namespace PrimeScore.Modules.Decision.Storage.Migrations
{
    [DbContext(typeof(DecisionDbContext))]
    partial class DecisionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("PrimeScore.Modules.Decision.Storage.DecisionRow", b =>
                {
                    b.Property<string>("DecisionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("decision_id");

                    b.Property<long>("AsOfMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("as_of_ms");

                    b.Property<string>("CompositeId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("composite_id");

                    b.Property<double>("CompositeScore")
                        .HasColumnType("REAL")
                        .HasColumnName("composite_score");

                    b.Property<int>("ConfigVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("config_version");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("context");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("correlation_id");

                    b.Property<string>("DislocationId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("dislocation_id");

                    b.Property<long>("DislocationSequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dislocation_sequence");

                    b.Property<double>("DislocationThreshold")
                        .HasColumnType("REAL")
                        .HasColumnName("dislocation_threshold");

                    b.Property<double>("DislocationValue")
                        .HasColumnType("REAL")
                        .HasColumnName("dislocation_value");

                    b.Property<double>("MarketObservedIv")
                        .HasColumnType("REAL")
                        .HasColumnName("market_observed_iv");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("outcome");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.Property<long>("RecordedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recorded_at_ms");

                    b.Property<string>("ReferenceInstrument")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reference_instrument");

                    b.Property<string>("Scenario")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("scenario");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ledger_sequence");

                    b.Property<double>("SignalImpliedIv")
                        .HasColumnType("REAL")
                        .HasColumnName("signal_implied_iv");

                    b.Property<string>("TriggerSignalId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("trigger_signal_id");

                    b.HasKey("DecisionId");

                    b.HasIndex("AsOfMs")
                        .HasDatabaseName("ix_dec_decisions_time");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_dec_decisions_correlation");

                    b.HasIndex("DislocationSequence")
                        .IsUnique()
                        .HasDatabaseName("ux_dec_decisions_dislocation");

                    b.HasIndex("Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_dec_decisions_sequence");

                    b.HasIndex("Context", "AsOfMs", "Sequence")
                        .HasDatabaseName("ix_dec_decisions_context_time");

                    b.ToTable("dec_decisions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
