// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimeScore.Modules.Analytics.Storage;

#nullable disable

namespace PrimeScore.Modules.Analytics.Storage.Migrations
{
    [DbContext(typeof(ReplayDbContext))]
    [Migration("20260925111741_InitialAnalytics")]
    partial class InitialAnalytics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("PrimeScore.Modules.Analytics.Storage.ReplayRow", b =>
                {
                    b.Property<string>("ReplayId")
                        .HasColumnType("TEXT")
                        .HasColumnName("replay_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ledger_sequence");

                    b.HasKey("ReplayId");

                    b.HasIndex("Sequence")
                        .IsUnique();

                    b.ToTable("ana_replays", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
